FROM openjdk:11-jdk-oracle
MAINTAINER tomasoares@gmail.com
COPY target/codigo-postal-0.0.1-SNAPSHOT.jar codigo-postal-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "codigo-postal-0.0.1-SNAPSHOT.jar"]


